<?php

namespace App\Http\Controllers\Voyager;

use Illuminate\Http\Request;
use TCG\Voyager\Http\Controllers\VoyagerMediaController as BaseVoyagerMediaController;

class VoyagerMediaController extends BaseVoyagerMediaController
{
    public function upload(Request $request)
    {
        $parent = parent::upload($request); // TODO: Change the autogenerated stub
        if($request->is_builder){
            $folder = $request->upload_path;
            return response()->json(['data' => url('/storage/'.$parent->original['path'])]);
            $request->request->set('folder', $request->upload_path);
            $data = $this->files($request);
            $tmp = [];

            return response()->json(['data' => $tmp]);
        }else{
            return $parent;
        }
    }
}
