<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = ['email', 'comment', 'foreign_key', 'type', 'user_id', 'attachments'];
    public function getCreatedAtAttribute($data){
        return Carbon::parse($data)->format('Y-m-d');
    }
    public function getAttachmentsAttribute($data){
        if($data){
            return json_decode($data);
        }else return [];
    }
    public function user(){
        return $this->belongsTo('App\User');
    }
    public function rates(){
        return $this->hasMany('App\Rate', 'foreign_key')->where('table', 'comments');
    }
    public function delete()
    {
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
